"use client";

import { useCallback, useEffect, useRef } from "react";
import { FileText } from "lucide-react";
import { jsPDF } from "jspdf";
import { Button } from "@/components/ui/button";

type PdfField = {
  label: string;
  value: string;
};

interface EnrollmentConfirmationPdfButtonProps {
  subjectType: "estudiante" | "profesor";
  fullName: string;
  identification: string;
  fields: PdfField[];
  autoGenerateOnMount?: boolean;
}

export function EnrollmentConfirmationPdfButton({
  subjectType,
  fullName,
  identification,
  fields,
  autoGenerateOnMount = false,
}: EnrollmentConfirmationPdfButtonProps) {
  const hasAutoGeneratedRef = useRef(false);

  const handleGeneratePdf = useCallback(async () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const horizontalPadding = 16;
    const headerHeight = 28;
    const headerRed = { r: 61, g: 16, b: 15 };
    const headerRedDark = { r: 185, g: 28, b: 28 };
    let y = 20;

    const logoDataUrl = await fetch("/logos/LogoCircular_HE.PNG")
      .then(async (response) => {
        if (!response.ok) {
          return null;
        }

        const blob = await response.blob();
        return await new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.onload = () => resolve(reader.result as string);
          reader.onerror = () => reject(new Error("No se pudo cargar el logo"));
          reader.readAsDataURL(blob);
        });
      })
      .catch(() => null);

    const drawHeader = () => {
      doc.setFillColor(headerRed.r, headerRed.g, headerRed.b);
      doc.rect(0, 0, pageWidth, headerHeight, "F");

      doc.setDrawColor(headerRedDark.r, headerRedDark.g, headerRedDark.b);
      doc.line(0, headerHeight, pageWidth, headerHeight);

      if (logoDataUrl) {
        const logoSize = 18;
        doc.addImage(
          logoDataUrl,
          "PNG",
          pageWidth - horizontalPadding - logoSize,
          6,
          logoSize,
          logoSize,
        );
      }
    };

    const truncateToWidth = (text: string, maxWidth: number) => {
      const normalized = text.replace(/\s+/g, " ").trim();
      if (!normalized) return "N/A";
      if (doc.getTextWidth(normalized) <= maxWidth) return normalized;

      const ellipsis = "...";
      let result = normalized;
      while (
        result.length > 0 &&
        doc.getTextWidth(result + ellipsis) > maxWidth
      ) {
        result = result.slice(0, -1);
      }

      return result ? `${result}${ellipsis}` : ellipsis;
    };

    drawHeader();

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(
      "Confirmación de Registro en el Sistema de Harvard Enterprise",
      horizontalPadding,
      12,
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(
      `Comprobante de registro de ${subjectType}`,
      horizontalPadding,
      19,
    );

    doc.setTextColor(17, 24, 39);
    y = 36;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(fullName, horizontalPadding, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Identificación: ${identification}`, horizontalPadding, y);
    y += 6;

    doc.text(
      `Fecha de emision: ${new Date().toLocaleString("es-CO")}`,
      horizontalPadding,
      y,
    );
    y += 8;

    doc.setDrawColor(229, 231, 235);
    doc.line(horizontalPadding, y, pageWidth - horizontalPadding, y);
    y += 5;

    const contentTopY = y;
    const contentBottomY = pageHeight - 12;
    const availableHeight = contentBottomY - contentTopY;
    const columnGap = 8;
    const columnWidth = (pageWidth - horizontalPadding * 2 - columnGap) / 2;
    const rowsPerColumn = Math.max(1, Math.ceil(fields.length / 2));
    const rowHeight = Math.max(6, availableHeight / rowsPerColumn);
    const labelOffset = 2.8;
    const valueOffset = 5.6;

    doc.setDrawColor(235, 235, 235);

    fields.forEach(({ label, value }, index) => {
      const columnIndex = index % 2;
      const rowIndex = Math.floor(index / 2);
      const x = horizontalPadding + columnIndex * (columnWidth + columnGap);
      const rowY = contentTopY + rowIndex * rowHeight;
      const lineY = rowY + rowHeight;

      if (lineY > contentBottomY) {
        return;
      }

      doc.line(x, lineY, x + columnWidth, lineY);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      const labelText = truncateToWidth(`${label}:`, columnWidth - 1);
      doc.text(labelText, x, rowY + labelOffset);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.4);
      const safeValue = value && value.trim() !== "" ? value : "N/A";
      const valueText = truncateToWidth(safeValue, columnWidth - 1);
      doc.text(valueText, x, rowY + valueOffset);
    });

    const safeType = subjectType.replace(/\s+/g, "-");
    doc.save(`confirmacion-matricula-${safeType}-${identification}.pdf`);
  }, [fields, identification, fullName, subjectType]);

  useEffect(() => {
    if (!autoGenerateOnMount || hasAutoGeneratedRef.current) {
      return;
    }

    hasAutoGeneratedRef.current = true;
    void handleGeneratePdf();
  }, [autoGenerateOnMount, handleGeneratePdf]);

  return (
    <Button type="button" variant="outline" onClick={handleGeneratePdf}>
      <FileText className="mr-2 h-4 w-4" />
      Confirmación de Registro en el Sistema (PDF)
    </Button>
  );
}
